Repository dasch-swiss/dsp-js-lib, pull requests merged in 2019-09, with the labels that each got.

#14 Wip/parse resources
  .idea/knora-api-js-lib.iml
  src/api/endpoint.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/api/v2/ontology/ontologies-endpoint.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.ts
  src/api/v2/v2-endpoint.ts
  src/cache/OntologyCache.spec.ts
  src/cache/OntologyCache.ts
  src/models/v2/Constants.ts
  src/models/v2/CustomConverters.ts
  src/models/v2/ontologies/OntologyConversionUtil.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/ontologies/property-definition.ts
  src/models/v2/ontologies/read-ontology.ts
  src/models/v2/ontologies/resource-class-definition.ts
  src/models/v2/ontologies/resource-property-definition.ts
  src/models/v2/ontologies/standoff-class-definition.ts
  src/models/v2/ontologies/system-property-definition.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/read-resource.ts
  src/models/v2/resources/values/read-boolean-value.ts
  src/models/v2/resources/values/read-color-value.ts
  src/models/v2/resources/values/read-date-value.ts
  src/models/v2/resources/values/read-decimal-value.ts
  src/models/v2/resources/values/read-file-value.ts
  src/models/v2/resources/values/read-geom-value.ts
  src/models/v2/resources/values/read-int-value.ts
  src/models/v2/resources/values/read-interval-value.ts
  src/models/v2/resources/values/read-link-value.ts
  src/models/v2/resources/values/read-list-value.ts
  src/models/v2/resources/values/read-text-value.ts
  src/models/v2/resources/values/read-uri-value.ts
  src/models/v2/resources/values/read-value.ts
  test/data/api/v2/mockOntology.ts
  test/data/api/v2/ontologies/anything-ontology-expanded.json
  test/data/api/v2/ontologies/anything-ontology.json
  test/data/api/v2/ontologies/incunabula-ontology-expanded.json
  test/data/api/v2/ontologies/incunabula-ontology.json
  test/data/api/v2/ontologies/knora-api-ontology-expanded.json
  test/data/api/v2/ontologies/mls-ontology.json
  test/data/api/v2/resources/page-expanded.json
  test/data/api/v2/resources/page.json
  test/data/api/v2/resources/region-expanded.json
  test/data/api/v2/resources/region.json
  test/data/api/v2/resources/testding-expanded.json
  test/data/api/v2/resources/testding.json
  test/data/api/v2/resources/things-expanded.json
  test/data/api/v2/resources/things.json
Labels: enhancement

#32 Simplify Access of Values of a ReadResource
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/read-resource.ts
Labels: enhancement

#40 feature (resource and value): add missing properties
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/date-time-stamp-converter.ts
  src/models/v2/ontologies/read-ontology.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/read-resource.ts
  src/models/v2/resources/values/read-value.ts
Labels: enhancement

#42 Search endpoint
  src/api/endpoint.spec.ts
  src/api/endpoint.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/api/v2/search/search-endpoint.ts
  src/api/v2/v2-endpoint.ts
  src/models/v2/Constants.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/search/count-query-response.ts
  test/data/api/v2/search/count-query-result.json
Labels: feature

#33 Cache for List Nodes
  expand-jsonld-test-data-files.js
  src/api/v2/list/lists-endpoint.spec.ts
  src/api/v2/list/lists-endpoint.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/api/v2/search/search-endpoint.ts
  src/api/v2/v2-endpoint.ts
  src/cache/GenericCache.ts
  src/cache/ListNodeCache.spec.ts
  src/cache/ListNodeCache.ts
  src/cache/OntologyCache.spec.ts
  src/cache/OntologyCache.ts
  src/cache/UserCache.spec.ts
  src/cache/UserCache.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/lists/list-conversion-util.ts
  src/models/v2/lists/list-node.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/values/read-list-value.ts
  test/data/api/v2/lists/listnode-expanded.json
  test/data/api/v2/lists/listnode.json
  test/data/api/v2/lists/othertreelist-expanded.json
  test/data/api/v2/lists/othertreelist.json
  test/data/api/v2/lists/treelist-expanded.json
  test/data/api/v2/lists/treelist.json
  test/data/api/v2/mockList.ts
Labels: enhancement, feature

#44 feature (ontology): add missing properties
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/gui-attribute-converter.ts
  src/models/v2/custom-converters/has-cardinality-for-property-converter.ts
  src/models/v2/lists/list-node.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/ontologies/resource-class-definition.ts
  src/models/v2/ontologies/resource-property-definition.ts
Labels: enhancement

#56 Integrate v2 test data
  integrate-generated-files-admin.sh
  package.json
  scripts/expand-jsonld-test-data-files.js
  scripts/integrate-files-v2.js
  scripts/v2-test-data-config.json
  src/api/v2/list/lists-endpoint.spec.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/cache/ListNodeCache.spec.ts
  src/cache/OntologyCache.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  test/data/api/v2/lists/othertreelist-expanded.json
  test/data/api/v2/mockOntology.ts
  test/data/api/v2/ontologies/anything-ontology-expanded.json
  test/data/api/v2/ontologies/anything-ontology.json
  test/data/api/v2/ontologies/incunabula-ontology-expanded.json
  test/data/api/v2/ontologies/incunabula-ontology.json
  test/data/api/v2/ontologies/knora-api-ontology-expanded.json
  test/data/api/v2/ontologies/knora-api-ontology.json
  test/data/api/v2/ontologies/minimal-ontology-expanded.json
  test/data/api/v2/ontologies/minimal-ontology.json
  test/data/api/v2/resources/page-expanded.json
  test/data/api/v2/resources/page.json
  test/data/api/v2/resources/region-expanded.json
  test/data/api/v2/resources/region.json
  test/data/api/v2/resources/regions-expanded.json
  test/data/api/v2/resources/regions.json
  test/data/api/v2/resources/testding-expanded.json
  test/data/api/v2/resources/testding.json
  test/data/api/v2/resources/things-expanded.json
  test/data/api/v2/resources/things.json
  test/data/api/v2/search/count-query-result.json
Labels: enhancement, testing

#46 Specify value type of property
  .travis.yml
  src/index.ts
  src/models/v2/ontologies/EntityDefinition.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/ontologies/property-definition.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/read-resource.ts
  src/models/v2/resources/type-guard.ts
Labels: enhancement

#61 Wip/60 update packages
  package-lock.json
  package.json
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/cache/UserCache.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  test/data/api/v2/mockList.ts
Labels: enhancement

#66 ReadValue: add missing properties to constructor
  src/models/v2/resources/values/read-date-value.ts
  src/models/v2/resources/values/read-geom-value.ts
  src/models/v2/resources/values/read-value.ts
Labels: bug
