Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-01, with the labels that each got.

#135 Automate client code integration
  Makefile
Labels: testing

#58 Adapt parsing of an ontology's lastModificationDate
  .travis.yml
  src/models/v2/custom-converters/date-time-stamp-converter.ts
  src/models/v2/ontologies/ontology-metadata.ts
  src/models/v2/ontologies/read-ontology.ts
  src/models/v2/resources/create/create-resource.ts
  src/models/v2/resources/delete/delete-resource.ts
  src/models/v2/resources/read/read-resource.ts
  src/models/v2/resources/update/update-resource-metadata.ts
  src/models/v2/resources/values/read/read-value.ts
  test/data/api/v2/ontologies/all-ontology-metadata-expanded.json
  test/data/api/v2/ontologies/all-ontology-metadata.json
  test/data/api/v2/ontologies/anything-ontology-expanded.json
  test/data/api/v2/ontologies/anything-ontology.json
  test/data/api/v2/ontologies/minimal-ontology-expanded.json
  test/data/api/v2/ontologies/minimal-ontology.json
Labels: bug

#141 Add label to ReadOntology
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/models/v2/ontologies/read-ontology.ts
Labels: enhancement

#132 Fix publishing on npm
  README.md
  package.json
Labels: bug
