Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-12, with the labels that each got.

#258 DSP-1064 Create metadata endpoint in JS-LIB
  package.json
  src/api/v2/project-metadata/metadata-endpoint-v2.spec.ts
  src/api/v2/project-metadata/metadata-endpoint-v2.ts
  src/api/v2/v2-endpoint.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/date-converter.ts
  src/models/v2/custom-converters/date-time-stamp-converter.ts
  src/models/v2/custom-converters/distribution-converter.ts
  src/models/v2/custom-converters/email-converter.ts
  src/models/v2/custom-converters/person-organization-converter.ts
  src/models/v2/custom-converters/uri-converter.ts
  src/models/v2/custom-converters/url-to-object-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/project-metadata/address-definition.ts
  src/models/v2/project-metadata/attribution-definition.ts
  src/models/v2/project-metadata/data-management-plan-definition.ts
  src/models/v2/project-metadata/dataset-definition.ts
  src/models/v2/project-metadata/grant-definition.ts
  src/models/v2/project-metadata/organization-definition.ts
  src/models/v2/project-metadata/person-definition.ts
  src/models/v2/project-metadata/place-definition.ts
  src/models/v2/project-metadata/project-definition.ts
  src/models/v2/project-metadata/project-metadata.ts
  src/models/v2/project-metadata/update-project-metadata.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/package.json
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test-framework/src/assets/metadata-payload.json
  test-framework/tsconfig.json
Labels: enhancement

#266 DSP-1138 Add missing guiOrder to serialize IHasProperty
  src/models/v2/custom-converters/has-cardinality-for-property-converter.ts
Labels: bug

#265 Add Convenience Methods to Ontology Information
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/cache/ontology-cache/OntologyCache.spec.ts
  src/cache/ontology-cache/resource-class-and-property-definitions.ts
  src/models/v2/ontologies/ClassAndPropertyDefinitions.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/read/read-ontology.ts
Labels: enhancement

#271 DSP-1168 Release please action instead release drafter
  .github/release-drafter.yml
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  package.json
Labels: chore

#269 DSP-883 Support New Edit List Endpoints
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
  src/index.ts
  src/models/admin/child-node-info-response.ts
  src/models/admin/child-node-info.ts
  src/models/admin/update-child-node-comments-request.ts
  src/models/admin/update-child-node-labels-request.ts
  src/models/admin/update-child-node-name-request.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#273 Prepare release 1.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#268 DSP-1126 Finish metadata endpoint in JS-LIB
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/project-metadata/metadata-endpoint-v2.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/advanced-url-object-converter.ts
  src/models/v2/custom-converters/base-url-converter.ts
  src/models/v2/custom-converters/date-converter.ts
  src/models/v2/custom-converters/distribution-converter.ts
  src/models/v2/custom-converters/email-converter.ts
  src/models/v2/custom-converters/id-converter.ts
  src/models/v2/custom-converters/person-organization-converter.ts
  src/models/v2/custom-converters/place-converter.ts
  src/models/v2/custom-converters/url-to-object-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/project-metadata/address-definition.ts
  src/models/v2/project-metadata/address.ts
  src/models/v2/project-metadata/attribution-definition.ts
  src/models/v2/project-metadata/attribution.ts
  src/models/v2/project-metadata/base-project-metadata.ts
  src/models/v2/project-metadata/data-management-plan-definition.ts
  src/models/v2/project-metadata/data-management-plan.ts
  src/models/v2/project-metadata/dataset-definition.ts
  src/models/v2/project-metadata/dataset.ts
  src/models/v2/project-metadata/grant-definition.ts
  src/models/v2/project-metadata/grant.ts
  src/models/v2/project-metadata/metadata-conversion-util.ts
  src/models/v2/project-metadata/organization-definition.ts
  src/models/v2/project-metadata/organization.ts
  src/models/v2/project-metadata/person-definition.ts
  src/models/v2/project-metadata/person.ts
  src/models/v2/project-metadata/place-definition.ts
  src/models/v2/project-metadata/place.ts
  src/models/v2/project-metadata/project-definition.ts
  src/models/v2/project-metadata/project-metadata.ts
  src/models/v2/project-metadata/single-project.ts
  src/models/v2/project-metadata/update-project-metadata.ts
  test-framework/src/app/app.component.ts
  test-framework/src/assets/metadata-payload.json
  test-framework/tsconfig.json
Labels: enhancement

#275 Fix package name in release-please-action
  .github/workflows/main.yml
  CHANGELOG.md
Labels: chore

#279 Pass additional header options
  src/api/endpoint.spec.ts
  src/api/endpoint.ts
  src/api/v2/search/search-endpoint.spec.ts
Labels: enhancement

#277 Automate API Docs Publication
  .github/workflows/main.yml
  README.md
  package.json
  scripts/typedoc-config.js
  src/models/v2/custom-converters/base-url-converter.ts
Labels: documentation

#282 chore(CI) Deactivate release-please
  .github/workflows/main.yml
Labels: chore

#283 chore(CI): Bring back release-please-action
  .github/workflows/main.yml
Labels: chore
