Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-05, with the labels that each got.

#180 Integrate mockresource
  Makefile
  package-lock.json
  package.json
  test-framework/src/app/app.component.ts
  test/data/api/v2/mock-resource.ts
Labels: release, testing

#181 Prepare Dev Package
  Makefile
  README.md
  package.json
  scripts/mock-exports.json
  scripts/prepare-dev-publication.js
Labels: testing

#184 Use tagged Knora version
  Makefile
Labels: testing

#183 Ontology Cache: Ignore third-party properties consistently
  design-documentation.md
  src/cache/OntologyCache.spec.ts
  src/cache/OntologyCache.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  test/data/api/v2/mock-ontology-assertions.ts
  test/data/api/v2/mockOntology.ts
Labels: bug

#185 Return property defs by type
  design-documentation.md
  src/api/v2/v2-endpoint.ts
  src/cache/ontology-cache/OntologyCache.spec.ts
  src/cache/ontology-cache/OntologyCache.ts
  src/cache/ontology-cache/resource-class-and-property-definitions.ts
  src/cache/ontology-cache/resource-class-definition-with-property-definition.ts
  src/index.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/cardinality-util.ts
  src/models/v2/resources/read/read-resource.ts
  test-framework/yalc.lock
  test/data/api/v2/mock-ontology-assertions.ts
  test/data/api/v2/mock-resource.ts
  test/data/api/v2/mockOntology.ts
Labels: enhancement, feature

#187 Explain how to build a local dev version
  README.md
Labels: enhancement

#188 Wip/prepare rc.1
  CHANGELOG.md
  Makefile
  package-lock.json
  package.json
Labels: release

#191 Rename package
  Makefile
  README.md
  package-lock.json
  package.json
  test-framework/README.md
  test-framework/package.json
  test-framework/src/app/app.component.ts
  test-framework/yalc.lock
Labels: breaking
