Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-10, with the labels that each got.

#244 Add missing exports for ResourcePropertyDefinitionWit…
  src/index.ts
  test-framework/src/app/app.component.ts
Labels: bug

#245 Security update for node-forge
  package-lock.json
Labels: chore

#243 DSP-676 Add Support for Additional Methods in Admin Permission Endpoint
  src/api/admin/permissions/permissions-endpoint-admin.ts
  src/api/admin/permissions/permissions-endpoint.spec.ts
  src/index.ts
  src/models/admin/admin-doap-base.ts
  src/models/admin/administrative-permission.ts
  src/models/admin/administrative-permissions-response.ts
  src/models/admin/create-admin-doap-base.ts
  src/models/admin/create-administrative-permission.ts
  src/models/admin/create-default-object-access-permission.ts
  src/models/admin/create-permission.ts
  src/models/admin/default-object-access-permission-response.ts
  src/models/admin/default-object-access-permission.ts
  src/models/admin/default-object-access-permissions-response.ts
  src/models/admin/project-permission.ts
  src/models/admin/project-permissions-response.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#246 DSP-743 Support the api route /health
  src/api/system/health/health-conversion-util.ts
  src/api/system/health/health-endpoint-system.ts
  src/api/system/health/health-endpoint.spec.ts
  src/api/system/system-endpoint.ts
  src/index.ts
  src/knora-api-connection.ts
  src/models/system/health-response.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/system/health/get-health-response.json
Labels: enhancement

#248 Update CHANGELOG
  CHANGELOG.md
Labels: documentation

#249 Explain integration with knora-api
  README.md
Labels: documentation

#250 Handle Empty Response when Requesting Ontologies for a Project
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/ontology-metadata.ts
Labels: bug

#251 DSP-817 Health Endpoint: integrate test data
  Makefile
  README.md
  package.json
  scripts/integrate-files-system.js
  src/api/system/health/health-endpoint.spec.ts
  test/data/api/system/health/get-health-response.json
  test/data/api/system/health/maintenance-mode-response.json
  test/data/api/system/health/response-headers.txt
  test/data/api/system/health/running-response.json
  test/data/api/system/health/stopped-response.json
Labels: testing

#252 DSP-920 Renaming default github branch to "main"
  .github/workflows/main.yml
  CHANGELOG.md
Labels: chore, documentation
