Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-07, with the labels that each got.

#212 Github CI: Workflow splited into single steps
  .github/workflows/main.yml
  Makefile
Labels: testing

#211 Use knora-api 13.0.0-rc.8
  .github/workflows/main.yml
  Makefile
  test/data/api/admin/groups/get-group-members-response.json
  test/data/api/admin/projects/get-project-admin-members-response.json
  test/data/api/admin/projects/get-project-members-response.json
  test/data/api/admin/users/create-user-with-custom-Iri-request.json
  test/data/api/admin/users/get-user-project-memberships-response.json
Labels: dependencies

#208 Create and delete ontology
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/cache/ontology-cache/OntologyCache.spec.ts
  src/cache/ontology-cache/OntologyCache.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/create/create-ontology.ts
  src/models/v2/ontologies/delete/delete-ontology-response.ts
  src/models/v2/ontologies/delete/delete-ontology.ts
  src/models/v2/ontologies/read/read-ontology.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/mockOntology.ts
  test/data/api/v2/ontologies/create-empty-foo-ontology-request-expanded.json
  test/data/api/v2/ontologies/create-empty-foo-ontology-request.json
  test/data/api/v2/ontologies/create-empty-foo-ontology-response-expanded.json
  test/data/api/v2/ontologies/create-empty-foo-ontology-response.json
  test/data/api/v2/ontologies/delete-foo-ontology-response-expanded.json
  test/data/api/v2/ontologies/delete-foo-ontology-response.json
Labels: feature

#216 Prerelease 1.0.0-rc.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#217 Update .grenrc
  .grenrc
Labels: chore

#220 chore: bump dsp-api (DSP-512)
  .github/workflows/main.yml
  Makefile
  test/data/api/admin/groups/create-group-with-custom-Iri-request.json
  test/data/api/admin/lists/create-list-with-custom-IRI-request.json
  test/data/api/admin/projects/create-project-with-custom-Iri-request.json
Labels: chore
