Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-11, with the labels that each got.

#255 DSP-978 generate changelog automatically
  .github/workflows/main.yml
  .gitignore
  .grenrc
  CHANGELOG.md
  README.md
  package.json
Labels: chore

#259 DSP-1035 - MockResource Rename Methods
  .gitignore
  test/data/api/v2/mock-resource.ts
Labels: breaking, refactor

#253 Read an Islamic Date
  src/api/v2/values/values-endpoint.spec.ts
  src/models/v2/resources/values/create/create-date-value.ts
  src/models/v2/resources/values/read/read-date-value.ts
  src/models/v2/resources/values/type-specific-interfaces/base-date-value.ts
  src/models/v2/resources/values/update/update-date-value.ts
  test/data/api/v2/manually-generated/get-islamic-date-value-response-expanded.json
  test/data/api/v2/manually-generated/get-islamic-date-value-response.json
Labels: bug, testing

#261 DSP-915 - Missing lastModificationDate property
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/resource-class-definition.ts
  src/models/v2/ontologies/resource-property-definition.ts
Labels: enhancement
