Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-08, with the labels that each got.

#223 Update process of release notes
  .github/workflows/main.yml
Labels: chore

#218 Create and delete resource class
  Makefile
  package.json
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/string-literal-to-string-converter.ts
  src/models/v2/custom-converters/string-literal-to-string-literal-array-converter.ts
  src/models/v2/custom-converters/subclass-of-converter.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/create/create-resource-class-payload.ts
  src/models/v2/ontologies/create/create-resource-class.ts
  src/models/v2/ontologies/delete/delete-ontology.ts
  src/models/v2/ontologies/resource-class-definition.ts
  src/models/v2/ontologies/update-ontology.ts
  src/models/v2/string-literal-v2.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/ontologies/create-class-without-cardinalities-request-expanded.json
  test/data/api/v2/ontologies/create-class-without-cardinalities-request.json
  test/data/api/v2/ontologies/create-class-without-cardinalities-response-expanded.json
  test/data/api/v2/ontologies/create-class-without-cardinalities-response.json
  tsconfig.json
Labels: enhancement

#225 Export IPermissions, IFulltextSearchParams, ILabelSearchParams interfaces
  src/api/v2/search/search-endpoint-v2.ts
  src/index.ts
  src/interfaces/models/v2/i-fulltext-search-params.ts
  src/interfaces/models/v2/i-label-search-params.ts
Labels: enhancement

#226 Prerelease v1.0.0 rc.6
  .grenrc
  CHANGELOG.md
  package-lock.json
  package.json
  test-framework/src/app/app.component.ts
Labels: release

#228 Prerelease 1.0.0-rc.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#229 Mock minimal ontology
  test/data/api/v2/mock-ontology.ts
Labels: enhancement

#230 Prepare next prerelease: 1.0.0-rc.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#231 Update knora api version to rc.12
  CHANGELOG.md
  Makefile
  package-lock.json
  package.json
Labels: dependencies
