Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-06, with the labels that each got.

#194 Fix bug ApiResonseError
  src/api/endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/models/api-response-error.ts
  test/mockajaxcall.ts
Labels: bug

#196 ontology IRI: ignore port if not running on localhost
  src/models/v2/ontologies/OntologyConversionUtil.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
Labels: bug

#198 Bug fix in npm publishing process
  .github/workflows/main.yml
Labels: bug

#200 Readme and workflow fix
  .github/workflows/main.yml
  .gitignore
  README.md
Labels: enhancement

#201 Preparation for next pre-release 1.0.0-rc.3
  .github/workflows/main.yml
  README.md
  package-lock.json
  package.json
Labels: release

#199 Mock Ontology Data
  Makefile
  scripts/mock-exports.json
  test-framework/src/app/app.component.ts
  test-framework/yalc.lock
  test/data/api/admin/mockProjects.ts
  test/data/api/v2/mockOntology.ts
Labels: testing

#206 Mock users
  scripts/mock-exports.json
  test-framework/src/app/app.component.ts
  test-framework/yalc.lock
  test/data/api/admin/mockUsers.ts
Labels: testing

#207 Prerelease 1.0.0-rc.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#204 Get ontologies by project iri
  .gitignore
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test-framework/yalc.lock
  test/data/api/v2/ontologies/get-ontologies-project-anything-response-expanded.json
  test/data/api/v2/ontologies/get-ontologies-project-anything-response.json
  test/data/api/v2/ontologies/get-ontologies-project-incunabula-response-expanded.json
  test/data/api/v2/ontologies/get-ontologies-project-incunabula-response.json
Labels: feature

#205 Use knora-api 13.0.0-rc.5
  Makefile
  src/api/v2/values/values-endpoint.spec.ts
  test/data/api/admin/lists/create-list-with-custom-IRI-request.json
  test/data/api/admin/projects/create-project-with-custom-Iri-request.json
  test/data/api/v2/values/create-int-value-response-expanded.json
  test/data/api/v2/values/create-int-value-response.json
Labels: dependencies

#209 fix: Replace DateDate by Date
  src/api/v2/resource/resources-endpoint-v2.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/delete/delete-resource.ts
  src/models/v2/resources/read/read-resource.ts
  src/models/v2/resources/update/update-resource-metadata.ts
Labels: enhancement
