Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-02, with the labels that each got.

#138 test (admin): adapt test for updateUserSystemAdminMembership
  src/api/admin/users/users-endpoint.spec.ts
  src/api/admin/users/users-endpoint.ts
Labels: breaking, enhancement

#59 Add support for time value
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/values/values-endpoint.spec.ts
  src/cache/OntologyCache.spec.ts
  src/models/v2/Constants.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  src/models/v2/resources/ResourcesConversionUtil.ts
  src/models/v2/resources/values/create/create-time-value.ts
  src/models/v2/resources/values/read/read-time-value.ts
  src/models/v2/resources/values/type-specific-interfaces/base-time-value.ts
  src/models/v2/resources/values/update/update-time-value.ts
  test/data/api/v2/ontologies/anything-ontology-expanded.json
  test/data/api/v2/ontologies/anything-ontology.json
  test/data/api/v2/ontologies/knora-api-ontology-expanded.json
  test/data/api/v2/ontologies/knora-api-ontology.json
  test/data/api/v2/resources/create-resource-with-values-request-expanded.json
  test/data/api/v2/resources/create-resource-with-values-request.json
  test/data/api/v2/resources/testding-expanded.json
  test/data/api/v2/resources/testding.json
  test/data/api/v2/values/create-time-value-request-expanded.json
  test/data/api/v2/values/create-time-value-request.json
  test/data/api/v2/values/get-time-value-response-expanded.json
  test/data/api/v2/values/get-time-value-response.json
  test/data/api/v2/values/update-time-value-request-expanded.json
  test/data/api/v2/values/update-time-value-request.json
Labels: feature

#147 tests (it): adapt assertions
  package-lock.json
  test-framework/e2e/src/app.e2e-spec.ts
Labels: testing

#144 Add util for handling of cardinalities
  src/index.ts
  src/models/v2/resources/cardinality-util.spec.ts
  src/models/v2/resources/cardinality-util.ts
Labels: feature

#142 Util for permission handling
  src/index.ts
  src/models/v2/resources/permission-util.spec.ts
  src/models/v2/resources/permission-util.ts
Labels: enhancement

#150 fix (index.ts): add time values to public api
  src/index.ts
Labels: bug

#151 feature (value): add uuid to write / update value response
  scripts/v2-test-data-config.json
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/values/values-endpoint.spec.ts
  src/models/v2/resources/values/write-value-response.ts
  test/data/api/v2/ontologies/knora-api-ontology-expanded.json
  test/data/api/v2/ontologies/knora-api-ontology.json
  test/data/api/v2/values/create-int-value-response-expanded.json
  test/data/api/v2/values/create-int-value-response.json
  test/data/api/v2/values/update-int-value-response-expanded.json
  test/data/api/v2/values/update-int-value-response.json
Labels: enhancement
