Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-09, with the labels that each got.

#233 Prerelease: 1.0.0-rc.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#236 Prerelease: 1.0.0-rc.11
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#237 DSP-671 Update dsp-api rc.16
  Makefile
  src/api/admin/permissions/permissions-endpoint-admin.ts
  src/api/admin/permissions/permissions-endpoint.spec.ts
  test/data/api/admin/permissions/create-administrative-permission-response.json
  test/data/api/admin/permissions/create-administrative-permission-withCustomIRI-response.json
  test/data/api/admin/permissions/create-defaultObjectAccess-permission-response.json
  test/data/api/admin/permissions/create-defaultObjectAccess-permission-withCustomIRI-response.json
  test/data/api/admin/permissions/get-administrative-permission-for-project-group-response.json
  test/data/api/admin/permissions/get-administrative-permissions-for-project-response.json
  test/data/api/admin/permissions/get-defaultObjectAccess-permissions-for-project-response.json
  test/data/api/admin/permissions/get-permissions-for-project-response.json
Labels: breaking, dependencies

#238 Prerelease v1.0.0-rc.12
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#235 DSP-428 Create res properties
  .gitignore
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/cache/ontology-cache/resource-class-definition-with-property-definition.ts
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/custom-converters/has-cardinality-for-property-converter.ts
  src/models/v2/custom-converters/subclass-of-converter.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/ontologies/create/add-cardinality-to-resource-class.ts
  src/models/v2/ontologies/create/create-resource-property-payload.ts
  src/models/v2/ontologies/create/create-resource-property.ts
  src/models/v2/ontologies/resource-property-definition.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/ontologies/add-cardinalities-to-class-nothing-request-expanded.json
  test/data/api/v2/ontologies/add-cardinalities-to-class-nothing-request.json
  test/data/api/v2/ontologies/add-cardinalities-to-class-nothing-response-expanded.json
  test/data/api/v2/ontologies/add-cardinalities-to-class-nothing-response.json
  test/data/api/v2/ontologies/create-link-property-request-expanded.json
  test/data/api/v2/ontologies/create-link-property-request.json
  test/data/api/v2/ontologies/create-link-property-response-expanded.json
  test/data/api/v2/ontologies/create-link-property-response.json
  test/data/api/v2/ontologies/create-value-property-request-expanded.json
  test/data/api/v2/ontologies/create-value-property-request.json
  test/data/api/v2/ontologies/create-value-property-response-expanded.json
  test/data/api/v2/ontologies/create-value-property-response.json
  tsconfig.json
Labels: enhancement

#240 Revert change for tsconfig
  tsconfig.json
Labels: bug

#241 DSP-702 Add template for PRs
  .github/pull_request_template.md
Labels: chore

#239 Refactor Ontologies Endpoint
  Makefile
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/index.ts
  src/models/v2/ontologies/create/create-resource-class-payload.ts
  src/models/v2/ontologies/create/create-resource-class.ts
  src/models/v2/ontologies/create/create-resource-property-payload.ts
  src/models/v2/ontologies/create/create-resource-property.ts
  src/models/v2/ontologies/delete/delete-ontology.ts
  src/models/v2/ontologies/delete/delete-resource-class.ts
  src/models/v2/ontologies/delete/delete-resource-property.ts
  src/models/v2/ontologies/update-delete-entity.ts
  src/models/v2/ontologies/update-ontology.ts
  src/models/v2/ontologies/update/update-ontology-resource-class-cardinality.ts
  src/models/v2/ontologies/update/update-ontology.ts
  test-framework/src/app/app.component.ts
Labels: refactor

#242 DSP-618 Update release process
  .github/release-drafter.yml
  .github/workflows/main.yml
  .grenrc
  Makefile
  README.md
  package-lock.json
  package.json
Labels: chore
