Repository dasch-swiss/dsp-js-lib, pull requests merged in 2020-04, with the labels that each got.

#171 Test Framework: Do Not Check for Exact Number of Search Results in E2E Tests
  test-framework/e2e/src/app.e2e-spec.ts
Labels: enhancement

#173 Add missing decorator
  .gitignore
  package.json
  src/index.ts
  src/models/v2/resources/values/create/create-interval-value.ts
  test-framework/yalc.lock
Labels: bug

#160 Updated json2typescript to 1.4.1
  package-lock.json
  package.json
  src/models/v2/resources/values/create/create-value.ts
  src/models/v2/resources/values/delete/delete-value.ts
  src/models/v2/resources/values/read/read-value.ts
  src/models/v2/resources/values/update/update-value.ts
  test-framework/yalc.lock
Labels: bug

#175 Fix Import from RxJS
  src/api/endpoint.ts
Labels: bug

#174 Add Missing Exports to Index.ts
  src/index.ts
  test-framework/src/app/app.component.ts
Labels: bug

#176 Make RxJS a Peer Dep
  Makefile
  README.md
  package-lock.json
  package.json
  rxjs.md
  test-framework/Dockerfile
  test-framework/package.json
  test-framework/src/app/app.component.ts
  test-framework/yalc.lock
Labels: bug, dependencies

#178 Export missing member
  src/index.ts
Labels: bug

#179 Add missing exports
  src/api/admin/admin-endpoint.ts
  src/api/admin/groups/groups-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/permissions/permissions-endpoint-admin.ts
  src/api/admin/projects/projects-endpoint-admin.ts
  src/api/admin/users/users-endpoint-admin.ts
  src/api/v2/authentication/authentication-endpoint-v2.ts
  src/api/v2/list/lists-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/resource/resources-endpoint-v2.ts
  src/api/v2/search/search-endpoint-v2.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/api/v2/v2-endpoint.ts
  src/api/v2/values/values-endpoint-v2.ts
  src/index.ts
Labels: bug

#172 Test Framework: Update from Angular 7 to Angular 9
  .github/workflows/main.yml
  package-lock.json
  test-framework/Dockerfile
  test-framework/angular.json
  test-framework/package.json
  test-framework/src/tsconfig.app.json
  test-framework/tsconfig.json
  test-framework/yalc.lock
  test-framework/yarn.lock
Labels: dependencies
