Repository dasch-swiss/dsp-js-lib, pull requests merged in 2021-02, with the labels that each got.

#310 feat(lists-endpoint): add support for deleting a list node(DSP-1049)
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
  src/index.ts
  src/models/admin/delete-list-node-response.ts
  src/models/admin/delete-list-response.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#312 feat(metadata-endpoint): test/implement flat response option (DSP-1223)
  src/api/v2/project-metadata/metadata-endpoint-v2.ts
  src/index.ts
  src/models/v2/custom-converters/base-url-converter.ts
  src/models/v2/custom-converters/distribution-converter.ts
  src/models/v2/custom-converters/place-converter.ts
  src/models/v2/custom-converters/union-advanced-url-object-converter.ts
  src/models/v2/custom-converters/union-data-management-plan-id-converter.ts
  src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
  src/models/v2/custom-converters/union-metadata-converter.ts
  src/models/v2/custom-converters/union-orgnization-id-converter.ts
  src/models/v2/custom-converters/union-person-organization-id-converter.ts
  src/models/v2/custom-converters/union-single-project-id-converter.ts
  src/models/v2/custom-converters/union-url-string-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/project-metadata/attribution.ts
  src/models/v2/project-metadata/data-management-plan.ts
  src/models/v2/project-metadata/dataset.ts
  src/models/v2/project-metadata/grant.ts
  src/models/v2/project-metadata/metadata-conversion-util.ts
  src/models/v2/project-metadata/metadata-interfaces.ts
  src/models/v2/project-metadata/organization.ts
  src/models/v2/project-metadata/person.ts
  src/models/v2/project-metadata/place.ts
  src/models/v2/project-metadata/project-metadata.ts
  src/models/v2/project-metadata/single-project.ts
  test-framework/src/app/app.component.ts
Labels: enhancement

#304 feat(ontology endpoint)!: replace cardinalities (DSP-1265)
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/cache/ontology-cache/resource-class-definition-with-property-definition.ts
  src/index.ts
  src/models/v2/custom-converters/has-cardinality-for-property-converter.ts
  src/models/v2/ontologies/class-definition.ts
  src/models/v2/ontologies/update/update-ontology.ts
  src/models/v2/ontologies/update/update-resource-class-cardinality.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/ontologies/remove-class-cardinalities-request-expanded.json
  test/data/api/v2/ontologies/remove-class-cardinalities-request.json
  test/data/api/v2/ontologies/replace-class-cardinalities-request-expanded.json
  test/data/api/v2/ontologies/replace-class-cardinalities-request.json
Labels: breaking, enhancement

#210 fix(cache)!: handle failed requests to dsp-api (DSP-402)
  design-documentation.md
  rxjs.md
  src/api/v2/resource/resources-endpoint.spec.ts
  src/api/v2/search/search-endpoint.spec.ts
  src/api/v2/values/values-endpoint.spec.ts
  src/cache/GenericCache.ts
  src/cache/ListAdminCache.ts
  src/cache/ListNodeV2Cache.spec.ts
  src/cache/ListNodeV2Cache.ts
  src/cache/UserCache.ts
  src/cache/ontology-cache/OntologyCache.spec.ts
  src/cache/ontology-cache/OntologyCache.ts
  src/models/v2/resources/ResourcesConversionUtil.spec.ts
  test-framework/src/app/app.component.html
  test/data/api/v2/mock-list.ts
  test/data/api/v2/mock-resource.ts
Labels: breaking, bug

#307 feat(permissions endpoint): Delete Permission (DSP-1304)
  src/api/admin/permissions/permissions-endpoint-admin.ts
  src/api/admin/permissions/permissions-endpoint.spec.ts
  src/index.ts
  src/models/admin/delete-permission-response.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#314 feat(metadata-endopoint)!: minor improvements + code refactoring (DSP-1307)
  src/index.ts
  src/interfaces/models/v2/project-metadata-interfaces.ts
  src/models/v2/custom-converters/base-url-converter.ts
  src/models/v2/custom-converters/distribution-converter.ts
  src/models/v2/custom-converters/place-converter.ts
  src/models/v2/custom-converters/union-advanced-url-object-converter.ts
  src/models/v2/custom-converters/union-data-management-plan-id-converter.ts
  src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
  src/models/v2/custom-converters/union-metadata-converter.ts
  src/models/v2/custom-converters/union-orgnization-id-converter.ts
  src/models/v2/custom-converters/union-person-organization-id-converter.ts
  src/models/v2/custom-converters/union-single-project-id-converter.ts
  src/models/v2/custom-converters/union-string-array-of-strings-converter.ts
  src/models/v2/custom-converters/union-url-string-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/project-metadata/attribution.ts
  src/models/v2/project-metadata/data-management-plan.ts
  src/models/v2/project-metadata/dataset.ts
  src/models/v2/project-metadata/grant.ts
  src/models/v2/project-metadata/organization.ts
  src/models/v2/project-metadata/person.ts
  src/models/v2/project-metadata/place.ts
  src/models/v2/project-metadata/single-project.ts
  test-framework/src/app/app.component.ts
Labels: breaking, enhancement, refactor

#316 feat (lists-endpoint): Add helper method for repositioning list node (DSP-1048)
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
  src/index.ts
  src/models/admin/delete-list-node-response.ts
  src/models/admin/list-node-response.ts
  src/models/admin/reposition-child-node-request.ts
  src/models/admin/reposition-child-node-response.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement, refactor

#321 fix(metadata-endpoint): ID conversion (DSP-1348)
  src/models/v2/custom-converters/union-data-management-plan-id-converter.ts
  src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
  src/models/v2/custom-converters/union-orgnization-id-converter.ts
  src/models/v2/custom-converters/union-person-organization-id-converter.ts
  src/models/v2/custom-converters/union-single-project-id-converter.ts
  src/models/v2/project-metadata/attribution.ts
  test-framework/src/app/app.component.ts
Labels: bug

#322 refactor(create-child-node-request): add optional position property (DSP-1300)
  src/api/admin/lists/lists-endpoint.spec.ts
  src/models/admin/create-child-node-request.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: refactor

#323 refactor(gh-ci): update release please configuration (DSP-1379)
  .github/workflows/main.yml
Labels: chore

#324 feat(lists-endpoint): Support for receiving a list child node from DSP-API (DSP-1385)
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
  src/index.ts
  src/models/admin/list-child-node-response.ts
  src/models/admin/list-child-node.ts
Labels: enhancement
