Repository dasch-swiss/dsp-js-lib, pull requests merged in 2021-09, with the labels that each got.

#368 chore(gh-ci): add code ql analysis to github actions
  .github/workflows/codeql-analysis.yml
Labels: chore

#369 chore(deps): fix security vulnerability
  package-lock.json
  package.json
  test-framework/package-lock.json
Labels: dependencies, chore

#374 feat(cache): reload cache methods (DSP-1913)
  src/cache/ListAdminCache.spec.ts
  src/cache/ListAdminCache.ts
  src/cache/ListNodeV2Cache.spec.ts
  src/cache/ListNodeV2Cache.ts
  src/cache/UserCache.spec.ts
  src/cache/UserCache.ts
  src/cache/ontology-cache/OntologyCache.spec.ts
  src/cache/ontology-cache/OntologyCache.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement
