Repository dasch-swiss/dsp-js-lib, pull requests merged in 2021-01, with the labels that each got.

#285 DSP-872 Missing constants in js-lib
  src/models/v2/Constants.ts
Labels: enhancement

#287 chore: Try to re-activate release pr
  .github/workflows/main.yml
Labels: chore

#281 DSP-1180 - Support Edit List Feature Toggle Endpoints
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
  src/index.ts
  src/models/admin/update-child-node-request.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/admin/manually-generated/update-node-info-name-comment-label-request.json
  test/data/api/admin/manually-generated/update-node-info-name-comment-label-response.json
Labels: enhancement

#286 feat(endpoint): Retry failed HTTP requests (DSP-170)
  src/api/endpoint.ts
  src/api/operators/retryOnError.spec.ts
  src/api/operators/retryOnError.ts
Labels: enhancement

#294 fix: metadata endpoint after DSP-API v.13.0.0 release (DSP-1232)
  src/api/v2/project-metadata/metadata-endpoint-v2.ts
  src/models/v2/custom-converters/place-converter.ts
  src/models/v2/project-metadata/metadata-conversion-util.ts
  test-framework/src/app/app.component.ts
Labels: bug

#299 feat(file value): export base file value classes (DSP-1262)
  src/index.ts
Labels: chore

#297 feat(ontology endpoint): get ontology in all langs (dsp-1230)
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/models/v2/ontologies/OntologyConversionUtil.ts
  src/models/v2/ontologies/standoff-class-definition.ts
  src/models/v2/ontologies/system-property-definition.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/manually-generated/minimal-ontology-with-all-languages-expanded.json
  test/data/api/v2/manually-generated/minimal-ontology-with-all-languages.json
Labels: enhancement

#302 fix(lists-endpoint): getListNodeInfo return types (DSP-1278)
  src/api/admin/lists/lists-endpoint-admin.ts
  src/api/admin/lists/lists-endpoint.spec.ts
Labels: bug

#303 feat(ontology endpoint): update a resource class's and property's label and comment (DSP-1263 / DSP-1264)
  .github/workflows/main.yml
  find-ignored-tests.sh
  scripts/v2-test-data-config.json
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/api/v2/ontology/ontologies-endpoint.spec.ts
  src/index.ts
  src/models/v2/ontologies/update/update-entity-comment-or-label.ts
  src/models/v2/ontologies/update/update-ontology.ts
  src/models/v2/ontologies/update/update-resource-class-comment.ts
  src/models/v2/ontologies/update/update-resource-class-label.ts
  src/models/v2/ontologies/update/update-resource-property-comment.ts
  src/models/v2/ontologies/update/update-resource-property-label.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
  test/data/api/v2/ontologies/change-class-comment-request-expanded.json
  test/data/api/v2/ontologies/change-class-comment-request.json
  test/data/api/v2/ontologies/change-class-label-request-expanded.json
  test/data/api/v2/ontologies/change-class-label-request.json
  test/data/api/v2/ontologies/change-property-comment-request-expanded.json
  test/data/api/v2/ontologies/change-property-comment-request.json
  test/data/api/v2/ontologies/change-property-label-request-expanded.json
  test/data/api/v2/ontologies/change-property-label-request.json
Labels: enhancement

#301 feat(ProjectMetadataEndpointV2): adjust x-n properties and custom converters (DSP-1222)
  src/api/v2/project-metadata/metadata-endpoint-v2.ts
  src/models/v2/custom-converters/advanced-url-object-converter.ts
  src/models/v2/custom-converters/base-url-converter.ts
  src/models/v2/custom-converters/distribution-converter.ts
  src/models/v2/custom-converters/id-converter.ts
  src/models/v2/custom-converters/person-organization-converter.ts
  src/models/v2/custom-converters/place-converter.ts
  src/models/v2/custom-converters/union-advanced-url-object-converter.ts
  src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
  src/models/v2/custom-converters/union-metadata-converter.ts
  src/models/v2/custom-converters/union-orgnization-id-converter.ts
  src/models/v2/custom-converters/union-person-organization-id-converter.ts
  src/models/v2/custom-converters/union-single-project-id-converter.ts
  src/models/v2/custom-converters/union-string-array-of-strings-converter.ts
  src/models/v2/custom-converters/union-url-string-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/project-metadata/attribution.ts
  src/models/v2/project-metadata/dataset.ts
  src/models/v2/project-metadata/grant.ts
  src/models/v2/project-metadata/organization.ts
  src/models/v2/project-metadata/person.ts
  src/models/v2/project-metadata/place.ts
  src/models/v2/project-metadata/project-metadata.ts
  src/models/v2/project-metadata/single-project.ts
  test-framework/src/app/app.component.ts
Labels: enhancement

#309 feat(metadata-endpoint): expose all x-n properties as arrays (DSP-1306)
  src/models/v2/custom-converters/union-element-array-of-elements-converter.ts
  src/models/v2/custom-converters/union-orgnization-id-converter.ts
  src/models/v2/custom-converters/union-person-organization-id-converter.ts
  src/models/v2/custom-converters/union-string-array-of-strings-converter.ts
  src/models/v2/custom-converters/union-url-string-converter.ts
  src/models/v2/custom-converters/url-to-url-object-converter.ts
  src/models/v2/project-metadata/attribution.ts
  src/models/v2/project-metadata/dataset.ts
  src/models/v2/project-metadata/grant.ts
  src/models/v2/project-metadata/organization.ts
  src/models/v2/project-metadata/person.ts
  src/models/v2/project-metadata/single-project.ts
  src/models/v2/project-metadata/update-project-metadata.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement
