Repository dasch-swiss/dsp-js-lib, pull requests merged in 2021-07, with the labels that each got.

#350 feat(ontology): new method to update gui element and attributes (DSP-1768)
  src/api/v2/ontology/ontologies-endpoint-v2.ts
  src/index.ts
  src/models/v2/ontologies/update/update-resource-property-gui-element.ts
  src/models/v2/ontologies/update/update-resource-property-label.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/package-lock.json
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#352 feat(file-value): support all file value types (DSP-1777)
  src/index.ts
  src/models/v2/Constants.ts
  src/models/v2/resources/values/create/create-file-value.ts
  src/models/v2/resources/values/read/read-file-value.ts
  src/models/v2/resources/values/update/update-file-value.ts
Labels: enhancement

#354 chore(models): expand resource conversion (DSP-1795)
  src/models/v2/resources/ResourcesConversionUtil.ts
Labels: chore, enhancement

#356 fix(resource): optional file values (DSP-1803)
  src/models/v2/resources/values/read/read-file-value.ts
Labels: bug

#357 feat(resource): add erase resource method (DSP-1807)
  scripts/v2-test-data-config.json
  src/api/v2/resource/resources-endpoint-v2.ts
  src/api/v2/resource/resources-endpoint.spec.ts
  test/data/api/v2/ontologies/can-do-response-expanded.json
  test/data/api/v2/resources/erase-resource-request-expanded.json
  test/data/api/v2/resources/erase-resource-request.json
  test/data/api/v2/resources/erase-resource-response-expanded.json
  test/data/api/v2/resources/erase-resource-response.json
Labels: enhancement

#313 feat(permissions): update permissions (DSP-1317)
  src/api/admin/permissions/permissions-endpoint-admin.ts
  src/api/admin/permissions/permissions-endpoint.spec.ts
  src/index.ts
  src/models/admin/create-permission.ts
  src/models/admin/create-update-permission.ts
  src/models/admin/update-administrative-permission-group.ts
  src/models/admin/update-administrative-permission.ts
  src/models/admin/update-default-object-access-permission-group.ts
  src/models/admin/update-default-object-access-permission-property.ts
  src/models/admin/update-default-object-access-permission-resource-class.ts
  src/models/admin/update-default-object-access-permission.ts
  src/models/admin/update-permission-group.ts
  src/models/admin/update-permission.ts
  test-framework/e2e/src/app.e2e-spec.ts
  test-framework/src/app/app.component.html
  test-framework/src/app/app.component.ts
Labels: enhancement

#361 fix(endpoint)!: resolve set-cookie issue (DSP-1827)
  src/api/endpoint.ts
Labels: bug, enhancement
